/**
 * Photo shares — opaque tokens granting public read-only access to a
 * single photo. The token IS the capability: anyone with it can view
 * the photo without the session cookie. Revoke = delete the row.
 *
 * Tokens are 22-char URL-safe base64 (16 random bytes), generated by
 * the API endpoint rather than this module — keeps `crypto` out of the
 * db layer and lets callers swap the generator if needed.
 */
import { db } from "./connection";
import "./schema";

export interface PhotoShare {
  token: string;
  photo_id: number;
  created_at: number;
}

const shareStmts = {
  byToken: db.prepare<[string], PhotoShare>(
    "SELECT * FROM photo_shares WHERE token = ?",
  ),
  listForPhoto: db.prepare<[number], PhotoShare>(
    "SELECT * FROM photo_shares WHERE photo_id = ? ORDER BY created_at DESC",
  ),
  insert: db.prepare<[string, number, number]>(
    "INSERT INTO photo_shares (token, photo_id, created_at) VALUES (?, ?, ?)",
  ),
  delete: db.prepare<[string]>(
    "DELETE FROM photo_shares WHERE token = ?",
  ),
};

export const shareQueries = {
  /** Resolve a token to its share row, or null when no longer valid. */
  byToken(token: string): PhotoShare | null {
    return shareStmts.byToken.get(token) ?? null;
  },

  /** Active shares for a given photo, newest first. */
  listForPhoto(photoId: number): PhotoShare[] {
    return shareStmts.listForPhoto.all(photoId);
  },

  /** Persist a new share. Token must already be unique (caller generates it). */
  create(token: string, photoId: number): PhotoShare {
    const now = Date.now();
    shareStmts.insert.run(token, photoId, now);
    return { token, photo_id: photoId, created_at: now };
  },

  /** Revoke a share. Returns true if a row was actually removed. */
  delete(token: string): boolean {
    return shareStmts.delete.run(token).changes > 0;
  },
};
