/**
 * Photo shares — opaque tokens granting public read-only access to a
 * single photo. The token IS the capability: anyone with it can view
 * the photo without the session cookie. Revoke = delete the row.
 *
 * Tokens are 22-char URL-safe base64 (16 random bytes), generated by
 * the API endpoint rather than this module — keeps `crypto` out of the
 * db layer and lets callers swap the generator if needed.
 *
 * Each share also tracks `view_count` + `last_viewed_at`, bumped once
 * per landing-page render (`/s/:token`). The binary endpoint isn't
 * counted so a video player's range scrubs don't inflate the figure.
 */
import { db } from "./connection";
import "./schema";

export interface PhotoShare {
  token: string;
  photo_id: number;
  created_at: number;
  view_count: number;
  last_viewed_at: number | null;
}

/** Share row joined with just enough photo info to render the listing. */
export interface PhotoShareWithPhoto extends PhotoShare {
  photo_name: string;
  photo_kind: "photo" | "video";
  photo_developed_at: number;
}

const shareStmts = {
  byToken: db.prepare<[string], PhotoShare>(
    "SELECT * FROM photo_shares WHERE token = ?",
  ),
  listForPhoto: db.prepare<[number], PhotoShare>(
    "SELECT * FROM photo_shares WHERE photo_id = ? ORDER BY created_at DESC",
  ),
  listAll: db.prepare<[], PhotoShareWithPhoto>(`
    SELECT
      s.*,
      p.name         AS photo_name,
      p.kind         AS photo_kind,
      p.developed_at AS photo_developed_at
    FROM photo_shares s
    JOIN photos p ON p.id = s.photo_id
    ORDER BY s.created_at DESC
  `),
  insert: db.prepare<[string, number, number]>(
    "INSERT INTO photo_shares (token, photo_id, created_at) VALUES (?, ?, ?)",
  ),
  delete: db.prepare<[string]>(
    "DELETE FROM photo_shares WHERE token = ?",
  ),
  incrementView: db.prepare<[number, string]>(
    "UPDATE photo_shares SET view_count = view_count + 1, last_viewed_at = ? WHERE token = ?",
  ),
};

export const shareQueries = {
  /** Resolve a token to its share row, or null when no longer valid. */
  byToken(token: string): PhotoShare | null {
    return shareStmts.byToken.get(token) ?? null;
  },

  /** Active shares for a given photo, newest first. */
  listForPhoto(photoId: number): PhotoShare[] {
    return shareStmts.listForPhoto.all(photoId);
  },

  /**
   * Every active share across all photos. Joined with photos for the
   * thumbnail + name shown on the management view. Caller renders it
   * server-side so we don't ship an extra round-trip.
   */
  listAll(): PhotoShareWithPhoto[] {
    return shareStmts.listAll.all();
  },

  /** Persist a new share. Token must already be unique (caller generates it). */
  create(token: string, photoId: number): PhotoShare {
    const now = Date.now();
    shareStmts.insert.run(token, photoId, now);
    return {
      token,
      photo_id: photoId,
      created_at: now,
      view_count: 0,
      last_viewed_at: null,
    };
  },

  /** Revoke a share. Returns true if a row was actually removed. */
  delete(token: string): boolean {
    return shareStmts.delete.run(token).changes > 0;
  },

  /**
   * Bump the view counter for a token. Best-effort: silently no-ops
   * when the token has been revoked between the page render and this
   * call (rare, but possible).
   */
  recordView(token: string): void {
    shareStmts.incrementView.run(Date.now(), token);
  },
};
